version: "3"
services:
  dcs:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: dcs
    environment:
      - IPFS_PATH=/opt/dcs/data
    expose:
      - 4001
      - 8080
    ports:
      - 4001:4001
      - 5001:5001
      - 8090:8090
    volumes:
      - ./data:/opt/dcs/data:delegated
      - ./log:/opt/dcs/log:delegated
      - ./docker:/opt/dcs/docker:delegated
      - ./utils:/opt/dcs/utils:delegated
      - ./actions:/opt/dcs/actions:delegated
      - ./index.js:/opt/dcs/index.js:delegated
      - ./config.json:/opt/dcs/config.json:delegated
    working_dir: /opt/dcs
    command: sh ./docker/run.sh
    networks:
      - ipfs-network

networks:
  ipfs-network:
    driver: bridge
