version: "3"
services:
  dcs:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: dcs
    expose:
      - 4001
      - 8080
    ports:
      - 4001:4001
      - 5001:5001
      - 8090:8090
    volumes:
      - ./data:/opt/dcs/data
      - ./log:/opt/dcs/log
      - ./docker:/opt/dcs/docker
      - ./utils:/opt/dcs/utils
      - ./actions:/opt/dcs/actions
      - ./index.js:/opt/dcs/index.js
    working_dir: /opt/dcs
    command: sh ./docker/run.sh
    networks:
      - ipfs-network

networks:
  ipfs-network:
    driver: bridge
